language: ruby
rvm:
  - 1.9.3
env:
  - DB=postgresql
script:
  - RAILS_ENV=test bundle exec rake db:migrate
  - RAILS_ENV=test bundle exec rake
before_script:
  - psql -c 'create database mi_congreso_test' -U postgres