development:
  adapter: postgresql
  encoding: unicode
  database: mi_congreso_development
  username: postgres
  password:
  min_messages: ERROR
  pool: 5
  timeout: 5000
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: mi_congreso_test
  username: postgres
  password:
  min_messages: ERROR
  pool: 5
  timeout: 5000
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: mi_congreso_production
  username: postgres
  password:
  min_messages: ERROR
  pool: 5
  timeout: 5000
  host: localhost